# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/john/Programming/cpp/zengine

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/john/Programming/cpp/zengine

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/john/Programming/cpp/zengine/CMakeFiles /home/john/Programming/cpp/zengine/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/john/Programming/cpp/zengine/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named zengine

# Build rule for target.
zengine: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 zengine
.PHONY : zengine

# fast build rule for target.
zengine/fast:
	$(MAKE) -f CMakeFiles/zengine.dir/build.make CMakeFiles/zengine.dir/build
.PHONY : zengine/fast

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/zengine.dir/build.make CMakeFiles/zengine.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/zengine.dir/build.make CMakeFiles/zengine.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/zengine.dir/build.make CMakeFiles/zengine.dir/main.cpp.s
.PHONY : main.cpp.s

src/2D/asset.o: src/2D/asset.cpp.o

.PHONY : src/2D/asset.o

# target to build an object file
src/2D/asset.cpp.o:
	$(MAKE) -f CMakeFiles/zengine.dir/build.make CMakeFiles/zengine.dir/src/2D/asset.cpp.o
.PHONY : src/2D/asset.cpp.o

src/2D/asset.i: src/2D/asset.cpp.i

.PHONY : src/2D/asset.i

# target to preprocess a source file
src/2D/asset.cpp.i:
	$(MAKE) -f CMakeFiles/zengine.dir/build.make CMakeFiles/zengine.dir/src/2D/asset.cpp.i
.PHONY : src/2D/asset.cpp.i

src/2D/asset.s: src/2D/asset.cpp.s

.PHONY : src/2D/asset.s

# target to generate assembly for a file
src/2D/asset.cpp.s:
	$(MAKE) -f CMakeFiles/zengine.dir/build.make CMakeFiles/zengine.dir/src/2D/asset.cpp.s
.PHONY : src/2D/asset.cpp.s

src/2D/circle.o: src/2D/circle.cpp.o

.PHONY : src/2D/circle.o

# target to build an object file
src/2D/circle.cpp.o:
	$(MAKE) -f CMakeFiles/zengine.dir/build.make CMakeFiles/zengine.dir/src/2D/circle.cpp.o
.PHONY : src/2D/circle.cpp.o

src/2D/circle.i: src/2D/circle.cpp.i

.PHONY : src/2D/circle.i

# target to preprocess a source file
src/2D/circle.cpp.i:
	$(MAKE) -f CMakeFiles/zengine.dir/build.make CMakeFiles/zengine.dir/src/2D/circle.cpp.i
.PHONY : src/2D/circle.cpp.i

src/2D/circle.s: src/2D/circle.cpp.s

.PHONY : src/2D/circle.s

# target to generate assembly for a file
src/2D/circle.cpp.s:
	$(MAKE) -f CMakeFiles/zengine.dir/build.make CMakeFiles/zengine.dir/src/2D/circle.cpp.s
.PHONY : src/2D/circle.cpp.s

src/2D/fonttexture.o: src/2D/fonttexture.cpp.o

.PHONY : src/2D/fonttexture.o

# target to build an object file
src/2D/fonttexture.cpp.o:
	$(MAKE) -f CMakeFiles/zengine.dir/build.make CMakeFiles/zengine.dir/src/2D/fonttexture.cpp.o
.PHONY : src/2D/fonttexture.cpp.o

src/2D/fonttexture.i: src/2D/fonttexture.cpp.i

.PHONY : src/2D/fonttexture.i

# target to preprocess a source file
src/2D/fonttexture.cpp.i:
	$(MAKE) -f CMakeFiles/zengine.dir/build.make CMakeFiles/zengine.dir/src/2D/fonttexture.cpp.i
.PHONY : src/2D/fonttexture.cpp.i

src/2D/fonttexture.s: src/2D/fonttexture.cpp.s

.PHONY : src/2D/fonttexture.s

# target to generate assembly for a file
src/2D/fonttexture.cpp.s:
	$(MAKE) -f CMakeFiles/zengine.dir/build.make CMakeFiles/zengine.dir/src/2D/fonttexture.cpp.s
.PHONY : src/2D/fonttexture.cpp.s

src/2D/gameengine.o: src/2D/gameengine.cpp.o

.PHONY : src/2D/gameengine.o

# target to build an object file
src/2D/gameengine.cpp.o:
	$(MAKE) -f CMakeFiles/zengine.dir/build.make CMakeFiles/zengine.dir/src/2D/gameengine.cpp.o
.PHONY : src/2D/gameengine.cpp.o

src/2D/gameengine.i: src/2D/gameengine.cpp.i

.PHONY : src/2D/gameengine.i

# target to preprocess a source file
src/2D/gameengine.cpp.i:
	$(MAKE) -f CMakeFiles/zengine.dir/build.make CMakeFiles/zengine.dir/src/2D/gameengine.cpp.i
.PHONY : src/2D/gameengine.cpp.i

src/2D/gameengine.s: src/2D/gameengine.cpp.s

.PHONY : src/2D/gameengine.s

# target to generate assembly for a file
src/2D/gameengine.cpp.s:
	$(MAKE) -f CMakeFiles/zengine.dir/build.make CMakeFiles/zengine.dir/src/2D/gameengine.cpp.s
.PHONY : src/2D/gameengine.cpp.s

src/2D/geometry.o: src/2D/geometry.cpp.o

.PHONY : src/2D/geometry.o

# target to build an object file
src/2D/geometry.cpp.o:
	$(MAKE) -f CMakeFiles/zengine.dir/build.make CMakeFiles/zengine.dir/src/2D/geometry.cpp.o
.PHONY : src/2D/geometry.cpp.o

src/2D/geometry.i: src/2D/geometry.cpp.i

.PHONY : src/2D/geometry.i

# target to preprocess a source file
src/2D/geometry.cpp.i:
	$(MAKE) -f CMakeFiles/zengine.dir/build.make CMakeFiles/zengine.dir/src/2D/geometry.cpp.i
.PHONY : src/2D/geometry.cpp.i

src/2D/geometry.s: src/2D/geometry.cpp.s

.PHONY : src/2D/geometry.s

# target to generate assembly for a file
src/2D/geometry.cpp.s:
	$(MAKE) -f CMakeFiles/zengine.dir/build.make CMakeFiles/zengine.dir/src/2D/geometry.cpp.s
.PHONY : src/2D/geometry.cpp.s

src/2D/rectangle.o: src/2D/rectangle.cpp.o

.PHONY : src/2D/rectangle.o

# target to build an object file
src/2D/rectangle.cpp.o:
	$(MAKE) -f CMakeFiles/zengine.dir/build.make CMakeFiles/zengine.dir/src/2D/rectangle.cpp.o
.PHONY : src/2D/rectangle.cpp.o

src/2D/rectangle.i: src/2D/rectangle.cpp.i

.PHONY : src/2D/rectangle.i

# target to preprocess a source file
src/2D/rectangle.cpp.i:
	$(MAKE) -f CMakeFiles/zengine.dir/build.make CMakeFiles/zengine.dir/src/2D/rectangle.cpp.i
.PHONY : src/2D/rectangle.cpp.i

src/2D/rectangle.s: src/2D/rectangle.cpp.s

.PHONY : src/2D/rectangle.s

# target to generate assembly for a file
src/2D/rectangle.cpp.s:
	$(MAKE) -f CMakeFiles/zengine.dir/build.make CMakeFiles/zengine.dir/src/2D/rectangle.cpp.s
.PHONY : src/2D/rectangle.cpp.s

src/2D/texture.o: src/2D/texture.cpp.o

.PHONY : src/2D/texture.o

# target to build an object file
src/2D/texture.cpp.o:
	$(MAKE) -f CMakeFiles/zengine.dir/build.make CMakeFiles/zengine.dir/src/2D/texture.cpp.o
.PHONY : src/2D/texture.cpp.o

src/2D/texture.i: src/2D/texture.cpp.i

.PHONY : src/2D/texture.i

# target to preprocess a source file
src/2D/texture.cpp.i:
	$(MAKE) -f CMakeFiles/zengine.dir/build.make CMakeFiles/zengine.dir/src/2D/texture.cpp.i
.PHONY : src/2D/texture.cpp.i

src/2D/texture.s: src/2D/texture.cpp.s

.PHONY : src/2D/texture.s

# target to generate assembly for a file
src/2D/texture.cpp.s:
	$(MAKE) -f CMakeFiles/zengine.dir/build.make CMakeFiles/zengine.dir/src/2D/texture.cpp.s
.PHONY : src/2D/texture.cpp.s

src/3D/glcontext.o: src/3D/glcontext.cpp.o

.PHONY : src/3D/glcontext.o

# target to build an object file
src/3D/glcontext.cpp.o:
	$(MAKE) -f CMakeFiles/zengine.dir/build.make CMakeFiles/zengine.dir/src/3D/glcontext.cpp.o
.PHONY : src/3D/glcontext.cpp.o

src/3D/glcontext.i: src/3D/glcontext.cpp.i

.PHONY : src/3D/glcontext.i

# target to preprocess a source file
src/3D/glcontext.cpp.i:
	$(MAKE) -f CMakeFiles/zengine.dir/build.make CMakeFiles/zengine.dir/src/3D/glcontext.cpp.i
.PHONY : src/3D/glcontext.cpp.i

src/3D/glcontext.s: src/3D/glcontext.cpp.s

.PHONY : src/3D/glcontext.s

# target to generate assembly for a file
src/3D/glcontext.cpp.s:
	$(MAKE) -f CMakeFiles/zengine.dir/build.make CMakeFiles/zengine.dir/src/3D/glcontext.cpp.s
.PHONY : src/3D/glcontext.cpp.s

src/3D/mesh.o: src/3D/mesh.cpp.o

.PHONY : src/3D/mesh.o

# target to build an object file
src/3D/mesh.cpp.o:
	$(MAKE) -f CMakeFiles/zengine.dir/build.make CMakeFiles/zengine.dir/src/3D/mesh.cpp.o
.PHONY : src/3D/mesh.cpp.o

src/3D/mesh.i: src/3D/mesh.cpp.i

.PHONY : src/3D/mesh.i

# target to preprocess a source file
src/3D/mesh.cpp.i:
	$(MAKE) -f CMakeFiles/zengine.dir/build.make CMakeFiles/zengine.dir/src/3D/mesh.cpp.i
.PHONY : src/3D/mesh.cpp.i

src/3D/mesh.s: src/3D/mesh.cpp.s

.PHONY : src/3D/mesh.s

# target to generate assembly for a file
src/3D/mesh.cpp.s:
	$(MAKE) -f CMakeFiles/zengine.dir/build.make CMakeFiles/zengine.dir/src/3D/mesh.cpp.s
.PHONY : src/3D/mesh.cpp.s

src/3D/plane.o: src/3D/plane.cpp.o

.PHONY : src/3D/plane.o

# target to build an object file
src/3D/plane.cpp.o:
	$(MAKE) -f CMakeFiles/zengine.dir/build.make CMakeFiles/zengine.dir/src/3D/plane.cpp.o
.PHONY : src/3D/plane.cpp.o

src/3D/plane.i: src/3D/plane.cpp.i

.PHONY : src/3D/plane.i

# target to preprocess a source file
src/3D/plane.cpp.i:
	$(MAKE) -f CMakeFiles/zengine.dir/build.make CMakeFiles/zengine.dir/src/3D/plane.cpp.i
.PHONY : src/3D/plane.cpp.i

src/3D/plane.s: src/3D/plane.cpp.s

.PHONY : src/3D/plane.s

# target to generate assembly for a file
src/3D/plane.cpp.s:
	$(MAKE) -f CMakeFiles/zengine.dir/build.make CMakeFiles/zengine.dir/src/3D/plane.cpp.s
.PHONY : src/3D/plane.cpp.s

src/3D/shader.o: src/3D/shader.cpp.o

.PHONY : src/3D/shader.o

# target to build an object file
src/3D/shader.cpp.o:
	$(MAKE) -f CMakeFiles/zengine.dir/build.make CMakeFiles/zengine.dir/src/3D/shader.cpp.o
.PHONY : src/3D/shader.cpp.o

src/3D/shader.i: src/3D/shader.cpp.i

.PHONY : src/3D/shader.i

# target to preprocess a source file
src/3D/shader.cpp.i:
	$(MAKE) -f CMakeFiles/zengine.dir/build.make CMakeFiles/zengine.dir/src/3D/shader.cpp.i
.PHONY : src/3D/shader.cpp.i

src/3D/shader.s: src/3D/shader.cpp.s

.PHONY : src/3D/shader.s

# target to generate assembly for a file
src/3D/shader.cpp.s:
	$(MAKE) -f CMakeFiles/zengine.dir/build.make CMakeFiles/zengine.dir/src/3D/shader.cpp.s
.PHONY : src/3D/shader.cpp.s

src/3D/texture.o: src/3D/texture.cpp.o

.PHONY : src/3D/texture.o

# target to build an object file
src/3D/texture.cpp.o:
	$(MAKE) -f CMakeFiles/zengine.dir/build.make CMakeFiles/zengine.dir/src/3D/texture.cpp.o
.PHONY : src/3D/texture.cpp.o

src/3D/texture.i: src/3D/texture.cpp.i

.PHONY : src/3D/texture.i

# target to preprocess a source file
src/3D/texture.cpp.i:
	$(MAKE) -f CMakeFiles/zengine.dir/build.make CMakeFiles/zengine.dir/src/3D/texture.cpp.i
.PHONY : src/3D/texture.cpp.i

src/3D/texture.s: src/3D/texture.cpp.s

.PHONY : src/3D/texture.s

# target to generate assembly for a file
src/3D/texture.cpp.s:
	$(MAKE) -f CMakeFiles/zengine.dir/build.make CMakeFiles/zengine.dir/src/3D/texture.cpp.s
.PHONY : src/3D/texture.cpp.s

src/music.o: src/music.cpp.o

.PHONY : src/music.o

# target to build an object file
src/music.cpp.o:
	$(MAKE) -f CMakeFiles/zengine.dir/build.make CMakeFiles/zengine.dir/src/music.cpp.o
.PHONY : src/music.cpp.o

src/music.i: src/music.cpp.i

.PHONY : src/music.i

# target to preprocess a source file
src/music.cpp.i:
	$(MAKE) -f CMakeFiles/zengine.dir/build.make CMakeFiles/zengine.dir/src/music.cpp.i
.PHONY : src/music.cpp.i

src/music.s: src/music.cpp.s

.PHONY : src/music.s

# target to generate assembly for a file
src/music.cpp.s:
	$(MAKE) -f CMakeFiles/zengine.dir/build.make CMakeFiles/zengine.dir/src/music.cpp.s
.PHONY : src/music.cpp.s

src/sound.o: src/sound.cpp.o

.PHONY : src/sound.o

# target to build an object file
src/sound.cpp.o:
	$(MAKE) -f CMakeFiles/zengine.dir/build.make CMakeFiles/zengine.dir/src/sound.cpp.o
.PHONY : src/sound.cpp.o

src/sound.i: src/sound.cpp.i

.PHONY : src/sound.i

# target to preprocess a source file
src/sound.cpp.i:
	$(MAKE) -f CMakeFiles/zengine.dir/build.make CMakeFiles/zengine.dir/src/sound.cpp.i
.PHONY : src/sound.cpp.i

src/sound.s: src/sound.cpp.s

.PHONY : src/sound.s

# target to generate assembly for a file
src/sound.cpp.s:
	$(MAKE) -f CMakeFiles/zengine.dir/build.make CMakeFiles/zengine.dir/src/sound.cpp.s
.PHONY : src/sound.cpp.s

src/soundeffect.o: src/soundeffect.cpp.o

.PHONY : src/soundeffect.o

# target to build an object file
src/soundeffect.cpp.o:
	$(MAKE) -f CMakeFiles/zengine.dir/build.make CMakeFiles/zengine.dir/src/soundeffect.cpp.o
.PHONY : src/soundeffect.cpp.o

src/soundeffect.i: src/soundeffect.cpp.i

.PHONY : src/soundeffect.i

# target to preprocess a source file
src/soundeffect.cpp.i:
	$(MAKE) -f CMakeFiles/zengine.dir/build.make CMakeFiles/zengine.dir/src/soundeffect.cpp.i
.PHONY : src/soundeffect.cpp.i

src/soundeffect.s: src/soundeffect.cpp.s

.PHONY : src/soundeffect.s

# target to generate assembly for a file
src/soundeffect.cpp.s:
	$(MAKE) -f CMakeFiles/zengine.dir/build.make CMakeFiles/zengine.dir/src/soundeffect.cpp.s
.PHONY : src/soundeffect.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... zengine"
	@echo "... edit_cache"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... src/2D/asset.o"
	@echo "... src/2D/asset.i"
	@echo "... src/2D/asset.s"
	@echo "... src/2D/circle.o"
	@echo "... src/2D/circle.i"
	@echo "... src/2D/circle.s"
	@echo "... src/2D/fonttexture.o"
	@echo "... src/2D/fonttexture.i"
	@echo "... src/2D/fonttexture.s"
	@echo "... src/2D/gameengine.o"
	@echo "... src/2D/gameengine.i"
	@echo "... src/2D/gameengine.s"
	@echo "... src/2D/geometry.o"
	@echo "... src/2D/geometry.i"
	@echo "... src/2D/geometry.s"
	@echo "... src/2D/rectangle.o"
	@echo "... src/2D/rectangle.i"
	@echo "... src/2D/rectangle.s"
	@echo "... src/2D/texture.o"
	@echo "... src/2D/texture.i"
	@echo "... src/2D/texture.s"
	@echo "... src/3D/glcontext.o"
	@echo "... src/3D/glcontext.i"
	@echo "... src/3D/glcontext.s"
	@echo "... src/3D/mesh.o"
	@echo "... src/3D/mesh.i"
	@echo "... src/3D/mesh.s"
	@echo "... src/3D/plane.o"
	@echo "... src/3D/plane.i"
	@echo "... src/3D/plane.s"
	@echo "... src/3D/shader.o"
	@echo "... src/3D/shader.i"
	@echo "... src/3D/shader.s"
	@echo "... src/3D/texture.o"
	@echo "... src/3D/texture.i"
	@echo "... src/3D/texture.s"
	@echo "... src/music.o"
	@echo "... src/music.i"
	@echo "... src/music.s"
	@echo "... src/sound.o"
	@echo "... src/sound.i"
	@echo "... src/sound.s"
	@echo "... src/soundeffect.o"
	@echo "... src/soundeffect.i"
	@echo "... src/soundeffect.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

